import { defineStore } from 'pinia'

export const useCampaignStore = defineStore('campaigns', {
    state: () => ({
        campaigns: [
            {
                id: 1,
                name: 'Test Campaign 1',
                platform: 'Google',
                type: 'Search',
                client: 'Client 1',
                budget: 2000,
                currency: 'CHF',
                active: true,
            },
            {
                id: 2,
                name: 'Test Campaign 2',
                platform: 'Instagram',
                type: 'Video',
                client: 'Client 2',
                budget: 3000,
                currency: 'CHF',
                active: true,
            },
            {
                id: 3,
                name: 'Spring Sale',
                platform: 'Facebook',
                type: 'Banner',
                client: 'Client 3',
                budget: 1500,
                currency: 'USD',
                active: true,
            },
            {
                id: 4,
                name: 'Summer Campaign',
                platform: 'Twitter',
                type: 'Post',
                client: 'Client 4',
                budget: 2500,
                currency: 'EUR',
                active: false,
            },
            {
                id: 5,
                name: 'Holiday Special',
                platform: 'LinkedIn',
                type: 'Article',
                client: 'Client 5',
                budget: 1800,
                currency: 'CHF',
                active: true,
            },
            {
                id: 6,
                name: 'Winter Discount',
                platform: 'Google',
                type: 'Display',
                client: 'Client 6',
                budget: 2200,
                currency: 'GBP',
                active: true,
            },
            {
                id: 7,
                name: 'Black Friday Blitz',
                platform: 'Instagram',
                type: 'Story',
                client: 'Client 7',
                budget: 2700,
                currency: 'USD',
                active: false,
            },
            {
                id: 8,
                name: 'Cyber Monday',
                platform: 'Snapchat',
                type: 'Snap Ad',
                client: 'Client 8',
                budget: 3100,
                currency: 'EUR',
                active: true,
            },
            {
                id: 9,
                name: 'New Year New You',
                platform: 'YouTube',
                type: 'Video',
                client: 'Client 9',
                budget: 3500,
                currency: 'CHF',
                active: false,
            },
            {
                id: 10,
                name: "Valentine's Day Special",
                platform: 'Pinterest',
                type: 'Pin',
                client: 'Client 10',
                budget: 1900,
                currency: 'GBP',
                active: true,
            },
            {
                id: 11,
                name: 'Easter Promotions',
                platform: 'Facebook',
                type: 'Carousel',
                client: 'Client 11',
                budget: 2300,
                currency: 'USD',
                active: true,
            },
            {
                id: 12,
                name: 'Back to School',
                platform: 'Google',
                type: 'Search',
                client: 'Client 12',
                budget: 2600,
                currency: 'CHF',
                active: true,
            },
            {
                id: 13,
                name: 'Labor Day Sale',
                platform: 'Twitter',
                type: 'Post',
                client: 'Client 13',
                budget: 2100,
                currency: 'USD',
                active: true,
            },
            {
                id: 14,
                name: 'Halloween Special',
                platform: 'Instagram',
                type: 'Story',
                client: 'Client 14',
                budget: 3400,
                currency: 'EUR',
                active: true,
            },
        ],
    }),
    getters: {
        getCampaigns: (state) => state.campaigns,
    },
    actions: {},
})
